### ISSUE TITLE
OOM when passing files via xargs

### ISSUE THREAD

**Issue by matthiaskrgr** [shssoichiro/oxipng#125]
I tried compressing pngs of wesnoth https://github.com/wesnoth/wesnoth

```` find . | grep "\.png$" | xargs  oxipng -o6```` does reliably eat all my memory until oxipng is OOM-killed

a for loop that passes images one by one seems to work though
````
for i in `find . | grep "\.png$"` ; do ;                   
oxipng $i -o6
done
````

oxipng 2.0.0

**Comment by shssoichiro** [comment]
On which OS are you experiencing this? I was unable to reproduce this on Arch Linux x64 with 8 logical cores. Memory usage peaked just under 100MB, and there was no noticeable sign of a memory leak. `xargs` on Arch Linux does seem to batch the arguments, so that may be related. Some OSes may not do this.

**Comment by matthiaskrgr** [comment]
Hmm, I'm on manjaro and it takes around 20 seconds until all 16 gigs of memory of my machine are utilized (logical 2 cores, 4 threads).

**Comment by shssoichiro** [comment]
Never mind, I was running against an old version of oxipng. I was able to reproduce this against 2.0.0.

**Comment by shssoichiro** [comment]
Pushing 2.0.1 to fix this. It still exists behind the `cfzlib` feature, so anyone with this use case should avoid using that feature for now.
