### ISSUE TITLE
Dual purpose and implicit state in PngData

### ISSUE THREAD

**Issue by kornelski** [shssoichiro/oxipng#145]
`PngData` has both `idat_data` and `raw_data`, which are related, but used in different contexts and handled as independent fields.

This is problematic, because:

* It's possible to modify `raw_data` without invalidating `idat_data`. Currently the code has to keep track of that "manually" through a flag passed around. That feels fragile.

* Copying of `PngData` copies both of them, even when it's just for trials/reductions which are going to use only one of them.

* Alpha filter trials get `filtered_image` version of the idat that needs to be recompressed better later, but there's no way to store the filtered version, so later recompression does filtering again (that's very minor though).

I'm not entirely sure how this should be handled, but there must be a better way. Some ideas:

* Have separate CompressedPng and UncompressedPng objects, with only either raw or idat, and try to use them throughout the code accordingly.
* Have one body as enum `Compressed`/`Uncompressed`/`Both`
* Have getters/setters on PngData that clear `idat_data` when `raw_data` is set or borrowed mutably.

**Comment by andrews05** [comment]
In addition to the improvements made in #158 above, there have been further improvements with the addition of the raw API as optimisation is now performed on the `PngImage` rather than the `PngData`. There's probably still some tidy ups that could be done but I think the main concerns here are now resolved. (Correct me if I'm wrong @kornelski)
