### ISSUE TITLE
Option to preserve modification dates

### ISSUE THREAD

**Issue by kattjevfel** [shssoichiro/oxipng#166]
I'd like to start off by saying I highly appreciate what this software offers, but there is this one feature I miss.

In jpegoptim you can specify [--preserve](https://www.mankier.com/1/jpegoptim#--preserve) to not change the modification time of the file being optimized.
Could a similar feature be implemented into oxipng? Would make at least one user happy. ^^

**Comment by shssoichiro** [comment]
I'm sure there's a way to do this in oxipng, given that jpegoptim does it. Added as a feature request. Thanks!

**Comment by burneracctman** [comment]
I can't seem to get this feature to work.

**Comment by kattjevfel** [comment]
> I can't seem to get this feature to work.

That's because it's not implemented yet.

**Comment by moschroe** [comment]
I took this on because I like the tool and use it and timestamps are important for archiving purposes and various tools.

Working so far except on filesystems with `strictatime` mount option. Which is why it worked locally (`relatime`), but not on the github actions runners. Currently debugging the behaviour and FS interactions so I can write a reliable test.
