### ISSUE TITLE
Please add x86_64 windows binary release 

### ISSUE THREAD

**Issue by rorschach-py** [shssoichiro/oxipng#314]

**Comment by TPS** [comment]
https://github.com/shssoichiro/oxipng/issues/326#issuecomment-711260788 notes that v3.0.0 provides `x86_64`, just not v3.0.1.

**Comment by TPS** [comment]
@shssoichiro Is there any progress toward this? It'd solve @ least #326.

**Comment by shssoichiro** [comment]
I feel like at one point the CI did provide x86_64 images, and that was apparently removed at some point. It should produce both varieties.

**Comment by shssoichiro** [comment]
Turns out the deploy.yml actions script is configured to push both x86_64 and i686, but github actions is only running the i686 job (I assume because it comes later in the list). I'm trying to figure out how to workaround this issue in github actions, but am struggling to find documentation for how their include syntax works. Any Github Actions experts around? @Luni-4 possibly?

**Comment by Luni-4** [comment]
@shssoichiro 

Yep, it should be possible, i will look at it as soon as I can. Feel free to assign this issue to me, thanks! :)
