### ISSUE TITLE
Provide binary releases on GitHub

### ISSUE THREAD

**Issue by shssoichiro** [shssoichiro/oxipng#34]
Possibly using an automated tool such as https://github.com/japaric/rust-everywhere

**Comment by shssoichiro** [comment]
Wondering if anyone has familiarity with implementing this via rust-everywhere. I attempted it some time ago but was unable to get the CI builds to run successfully.

**Comment by TPS** [comment]
>Wondering if anyone has familiarity with implementing this via rust-everywhere. I attempted it some time ago but was unable to get the CI builds to run successfully.

@shssoichiro I hope @japaric could help, if asked nicely. :wink: :bow:

I'm especially interested in the `i686-pc-windows-gnu`, `i686-pc-windows-msvc`, `x86_64-pc-windows-gnu`, & `x86_64-pc-windows-msvc` targets, to propose for @javiergutierrezchamorro's [FileOptimizer](http://nikkhokkho.sourceforge.net/static.php?page=FileOptimizer), as a _multithreaded_ version of [OptiPNG](http://optipng.sourceforge.net/history.txt), since that tool seems to have only 1 enhancement since 2012, but mostly just bug fixes.

**Comment by sergeevabc** [comment]
Dear Josh,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by shssoichiro** [comment]
There should be (and it looks like there are for v2.2.0 and earlier, on the releases tab). It looks like the Windows builds broke at some point. I'll get those fixed up.

**Comment by 007** [comment]
I'd also like to :+1: for a statically-linked Linux build if you're setting up cross-compilation.
