### ISSUE TITLE
Oxipng writes the output file even when no reduction is possible

### ISSUE THREAD

**Issue by notr1ch** [shssoichiro/oxipng#436]
It seems if the file is already optimized, oxipng will write it again anyway, resulting in unnecessary changes to metadata like file timestamps. It would be nice if optimizing an already-optimized file was a no-op.

**Comment by Safari77** [comment]
It should write to a temporary file, then fsync it, then rename over the original file (or delete original file first on Windows) only if there were no problems in processing, writing, and fsyncing.
When using backup option, it should hardlink the original file to backup file, instead of the current processing where both backup and original files are lost in case of a system crash etc errors because they do not safely write the files.

**Comment by andrews05** [comment]
@notr1ch I'm pretty sure this shouldn't be happening unless you're using the `--force` option. Can you explain your situation a little more and show the full command you're using?

**Comment by notr1ch** [comment]
I can't seem to reproduce this any more, perhaps something fixed it in the interim.
