### ISSUE TITLE
Thinking about output validation

### ISSUE THREAD

**Issue by andrews05** [shssoichiro/oxipng#478]
I know I said I may not do any more work here, but I was thinking about the raw API in #376 which could be quite helpful for my use case. That led me to think about the output validation and how that would work for a raw API and I decided it might be worth having a separate discussion about it.

The issue with a raw API is that it may not be practical/easy to validate that the output pixels match the input pixels, since the input is raw data rather than a png image. This would also be an issue with hypothetical lossy options that may get added one day (e.g. forcing 16-bit to 8-bit). The validation also takes time and adds a bit to the binary size, so I think at the least it may be a good to idea to make it an optional feature.

That said, there may also be a case for simply removing it. I'm sure it has been a great help over oxipng's development but oxipng is quite stable and mature now, with an extensive test suite. Since 2019, there have been four different issues of "corrupt output" reported. One of these (#426) was a bug in oxipng resulting in mismatched pixels. Another one (#449) was a bug in zopfli resulting in an invalid file. The other two (#167 and #473) were bugs in the library used to perform the validation and not actually corrupt output, the latter of which is still waiting to be fixed. So it seems it may be causing just as many problems as it is solving.

If it were to be removed, we could instead use oxipng's own parsing to check that the output is a valid png. This should catch critical issues like the zopfli bug but not mismatched pixels. We would also want to continue using the existing validation for the tests, but keep it separate from oxipng itself.

What do you (or others) think?

**Comment by shssoichiro** [comment]
As you mentioned, the original intention of the output validation was indeed for development purposes. I didn't want someone using the program to end up with data loss if they encountered a bug in oxipng. I am on the fence about removing it entirely, but not opposed to it if there is a general opinion from the community that it is safe to remove the validation. If it is kept in place, I'd definitely be fine with adding a CLI flag to skip the validation, and for lossy compression we may just have to disable validation by default anyway, which kind of does make me lean more toward removing validation entirely. But I want to hear more opinions besides just my own.

**Comment by TPS** [comment]
Is it possible to put this validation behind a _compile_-time flag, so it's not built in the release, but can be accessed in a debug version when needed?

**Comment by andrews05** [comment]
Just to show some data:

| Validation | Speed at `-o0` | Binary size |
|-|-|-|
| Enabled | 11.5s | 2.07 MB |
| Disabled | 8.6s | 1.90 MB |

@TPS Yeah, it could be an optional "feature" like zopfli. If we opt to keep it, I think we should at least make it optional in this manner.

@RReverser @kornelski Do you have any thoughts here?

**Comment by AlexTMjugador** [comment]
I can provide some empirical data about output validation on a production setting. I've been using [a OxiPNG fork](https://github.com/ComunidadAylas/oxipng) with output validation removed for quite some time now (> 1 year). The fork is otherwise identical to some upstream OxiPNG commit. The images the app optimizes are user-provided, so it's very likely that it saw pretty bizarre PNGs. The app is open source and has thousands of downloads across different platforms.

In all this time, I have never noticed or received reports about OxiPNG producing corrupt output. However, I've seen faster execution times and smaller binary sizes, which are so welcome improvements for my use case, given that I use Zopfli mode, a ton of libraries, and decoding hundreds of images for a sanity check can be rather slow. In my experience, OxiPNG is stable, and doesn't practically benefit from this sanity check.

Nevertheless, I've never submitted a PR with this change because I had doubts about how appropriate it would be for the project. As it has been stated, it helped catching a Zopfli bug, and as a fellow developer, I completely understand that it helps spotting issues on development. But my experience shows that this sanity check serving a purpose is the exception rather than the norm, and it arguably is unwarranted to make OxiPNG noticeably less performant just because extremely unlikely bugs can happen. Most software doesn't handle cosmic rays flipping bits in memory :wink: 

In my opinion, the best course of action would be gating the sanity checks behind a feature flag enabled by default for debug builds, but not for the release builds distributed to end-users. To support advanced profiling and debugging use cases, I'd add a release-like [Cargo profile](https://doc.rust-lang.org/cargo/reference/profiles.html) that's identical to the release profile, but has these sanity checks enabled, to help catch bugs. Making it a CLI option sounds good to me too, but that approach lacks the binary size benefits of completely removing the sanity checks.

**Comment by kornelski** [comment]
I think it'd be fine to move it to `debug_assert`. It's useful for testing and development, but I also disable it in production for performance reasons.

**Comment by andrews05** [comment]
Thanks @AlexTMjugador @kornelski, that's really helpful.

@shssoichiro Happy to go ahead with this?
