### ISSUE TITLE
Support Windows 32 bit (x86) builds

### ISSUE THREAD

**Issue by ace-dent** [shssoichiro/oxipng#533]
I presume I could build for Windows 32bit?
i.e. Is there anything in the code base that relies on 64 bit? 
I'm hoping Rust is high level enough that any such optimizations are left to the compiler...

**Comment by AlexTMjugador** [comment]
It is possible to build Rust code for 32-bit CPUs, but the generated code is likely to perform worse because it won't be able to assume the availability of SIMD extensions which are required for x64 CPUs (e.g., SSE, SSE2, MMX). Of course, it's possible to generate 32-bit code that takes advantage of these extensions, but then the portability benefits of 32-bit code begin to fade away.

Why do you need 32-bit Windows builds in the first place?

**Comment by andrews05** [comment]
For reference, there was an issue with building 32-bit previously: #363

**Comment by ace-dent** [comment]
> Why do you need 32-bit Windows builds in the first place? 

@AlexTMjugador - Fair question! 😄 ... I like to contribute optimized png images to open source projects. For example, LibreOffice UI is built from `IconThemes` containing many thousands(!) of images. It's convenient to leave long running batch jobs like this utilising old hardware. Much of the niche png software is very old now, so will only ever be 32 bit anyway (if closed source). 

... There is an argument that end-of-life HW isn't the most efficient for energy use. Personally I still want to support ancient systems if possible. 🤷‍♂️ 

My other use case is running Windows Virtual Machines; the win32 VM takes slightly less resources on the host system.

**Comment by ace-dent** [comment]
> ... things stop working due to a lack of testing ...

@AlexTMjugador - very willing to help test any executables produced! 😃

**Comment by AlexTMjugador** [comment]
#534 resolved this.
