### ISSUE TITLE
Tolerate lowercase `-z` parameter

### ISSUE THREAD

**Issue by ace-dent** [shssoichiro/oxipng#539]
It seems odd that most parameters are lowercase (accept `-V`, due to collision)... but `-Z` requires uppercase...?
Is there a reason this was not lowercase?

**Comment by andrews05** [comment]
I can't comment on why it was designed that way but there's also the Pretend option which uses an uppercase P. It's not unusual (on unix/linux) for commands to have uppercase flags even when there's no conflict. Is there a particular difficulty this is causing?

**Comment by ace-dent** [comment]
Ok. Often executables are a bit more tolerant for parsing parameters... and tolerate Win oddities.
e.g. accepting `-`', `--` and `/` as equal; not being case sensitive, etc.
For the benefit of Windows users, perhaps explicitly document "parameters are case sensitive".

PS - Is it normal (or necessary) to distinguish '--long' / '-short' parameters by number of hyphens?

**Comment by andrews05** [comment]
'--long' / '-short' is very much standard practice and nothing to do with Rust (though the Clap library typically used in Rust programs necessarily works this way). The double hyphen for long arguments is "necessary" because a single hyphen allows you to specify multiple short arguments at once: `-Psavvo6` is equivalent to `--pretend --strip=safe --alpha --verbose --verbose --opt=6`.

**Comment by ace-dent** [comment]
Thanks @andrews05. Clearly an issue with the user ;-)
Perhaps we can cover some of this in the Docs?

**Comment by ace-dent** [comment]
Just realised my source of confusion! 
I was moving over a script that used `optipng`, for which all parameters are parsed with a single `-`....

**Comment by andrews05** [comment]
That should still work with oxipng though?

**Comment by andrews05** [comment]
Case sensitivity is now mentioned in the Read Me.
