### ISSUE TITLE
RFC: Removing the `backup` option

### ISSUE THREAD

**Issue by andrews05** [shssoichiro/oxipng#542]
Hi all, I'm hoping to get some feedback from users regarding the `backup` option. @AlexTMjugador and I very briefly discussed the possibility of removing this, so I want to outline why the idea came up and some reasons why we might want to do this.

**The issue:**
For user's of the API, the `backup` option is currently in the wrong place. It's provided as part of the main `Options` struct for all uses of the API, even though it's only relevant when outputting to a file. It would be appropriate to move the backup option to be part of the `OutFile` instead but the downside is that this makes the API more complicated to use.

**Why we might want to remove it**
- Removing it would reduce complexity.
- There's a strong possibility that nobody actually uses it.
- There's no particular use case for it.
- It's not typical practice for a program like this to provide such a feature.
- As best I understand, the feature exists in the first place because it was inherited from Optipng, which oxipng was originally based on. This is fine, but doesn't mean we need to keep it today.

**Why we might want to keep it**
- It's not really hurting - the API can happily remain as is.
- Somebody might be using it?

**Alternatives for people who might be using it**
- Output to a separate file/directory so as not to overwrite the original.
- Copy the file beforehand.
- Use proper backup software.
- Don't bother? Oxipng is super reliable these days and with an extensive test suite and no known corruption issues.

Any comments on this would be welcome 🙂

@shssoichiro Definitely keen to get your input also.

**Comment by TPS** [comment]
I fall heavily into the "Keep It" camp **_&_** do whatever you need to make it maintainable.

My biggest reason is something I didn't see above: it's an absolutely breaking change, & typically wouldn't be noticed by someone who updates to this version _(eventually, ahem)_ until something in their workflow breaks, & they must have those presumably backed-up files.

**Comment by andrews05** [comment]
Thanks for the input!
Breaking changes needn't be a concern. That's the whole point of semantic versioning and bumping the major version number - it signals that there are breaking changes and users should check the release notes to see how it might affect them.
There are already breaking changes for the next release, such as deinterlacing by default. Removing the backup option would actually be quite safe in the sense that if you tried to use it then it would error out due to an unrecognised option.

**Comment by ace-dent** [comment]
+1 for removing backup. Seems odd and unnecessary.
Please make sure that oxipng self-destructs if called with unknown parameters! 🔥 
(i.e. User will become aware that `-backup` was removed if oxipng doesn't run and reports an error to the CLI).

**Comment by andrews05** [comment]
@ace-dent good points!
- Unknown parameters: It does indeed error out.
- Check: This was added in #439, you can read the reasoning there. It does seem a little odd to me though.
- Pretend: I use this all the time when testing the code 😄. Not sure what the use case would be otherwise though.
- Fix: I'm inclined to agree. Currently all this does is skip the CRC check on each chunk and I can't imagine there could any security issues with this, but dealing with invalid files is probably best left to a different program. In Optipng I believe the fix option would skip all libpng warnings, which could potentially do a lot more though I'm not sure what exactly.

**Comment by andrews05** [comment]
A note regarding `check`: This can be effectively simulated with `--pretend --nx --nz -i keep` which will disable all optimisation.

**Comment by ace-dent** [comment]
> The -fix option is very niche, but very useful for those niches.

-- In the near 20yrs of experimenting with pngs, I have never found a broken CRC in the wild; only synthetic test images. I'm curious if anyone has ever genuinely found one?

> ... ignoring chunk CRCs is very handy for fuzzing OxiPNG...

-- A fair point. I just don't think `fix` is a good name for `ignore-crc`... Perhaps this (slight) misnomer can be addressed with tweaked Documentation / help?

**Comment by andrews05** [comment]
> -- In the near 20yrs of experimenting with pngs, I have never found a broken CRC in the wild; only synthetic test images. I'm curious if anyone has ever genuinely found one?

Yeah, was going to say the same. Data corruption (or bad png encoders) might have been a thing back in the nineties but it's effectively unheard of today.
Again keep in mind that oxipng was originally designed to replicate optipng, which included the `fix` option. Presumably the reason it specifically applies to CRCs here is simply because that's the most obvious/easy error to recover from, not because it was a commonly encountered error.

**Comment by ace-dent** [comment]
> Presumably the reason it specifically applies to CRCs here is simply because that's the most obvious/easy error to recover from ...

-- To state the obvious, in the real-world, if you cannot trust the CRC... I wouldn't want to trust what else of the bitstream is or isn't broken... 😅

**Comment by AlexTMjugador** [comment]
> [...] Data corruption (or bad png encoders) might have been a thing back in the nineties but it's effectively unheard of today.

For what it's worth, I've found from listening to user feedback on my apps that some popular PNG encoders (namely, those found in some versions of Photoshop and other image manipulation programs) do stupid things like adding trailing bytes to the PNG files they generate, even though [they violate the PNG specification](https://www.w3.org/TR/2003/REC-PNG-20031110/#15FileConformance). Of course, this does not mean that such encoders are broken to the point of generating chunks with bad CRCs, but this experience has shown me that it's not surprising to find blatant errors in PNG encoders in current usage.

Anyway, given that the maintenance cost of ignoring CRCs is low, that such an option is useful for fuzzing, and that safe Rust prevents memory safety problems that might arise from parsing potentially bad input, I'd just leave that option alone.

**Comment by Tristan971** [comment]
> Data corruption (or bad png encoders) might have been a thing back in the nineties but it's effectively unheard of today.

That is unfortunately not true. We originally PR'd the `check` option because we found ourselves regularly receiving PNG files from users that would result in optimization failures, with the main cause being Adler32 CRC mismatches. We see those errors around once a month on our production (so around ~1/350,000 PNG files we process).

We thus needed to do proper validation of those files. oxipng was already around and `--pretend` didn't fit the bill performance-wise, so we added `--check`. I elaborated a bit more in my answer to @andrews05 in https://github.com/shssoichiro/oxipng/pull/439#issuecomment-1666213193

That said, I don't think oxipng needs to be able to "fix" them. Merely meant to point out that it does happen in practice. We're plenty happy to just reject the file.

As for what encoders are at fault, in our experience it's usually some image manipulation programs. Wouldn't blame any in particular though, given it's hard to be sure how exactly "affected" users might have modified them.

**Comment by andrews05** [comment]
That's really interesting to hear, thanks for sharing! Are you saying that the images would be perfectly valid if the CRC was "fixed", or is that unknown?

**Comment by Tristan971** [comment]
> Are you saying that the images would be perfectly valid if the CRC was "fixed", or is that unknown?

We don't collect samples, alas [1]. So I can't say for sure.

But here's a sample file from our test suite: https://github.com/shssoichiro/oxipng/assets/875533/8587151b-c4cc-4215-b080-dcdb32c4577d

It does successfully render in most image viewers I try, but it fails oxipng processing (in the past with the adler32 error, nowadays with a less explicit 'Invalid data found; unable to read PNG file').

[1]: because ensuring perfect 1:1 pixel post-processing result is our main goal, so we reject anything even a little bit broken and don't take chances on automated fixes of any kind, in case they'd corrupt things and we'd realize it only months later with thousands of images subtly broken

**Comment by andrews05** [comment]
Oh I see, we've got slightly mixed up here. Adler32 is the zlib checksum; crc32 the PNG chunk checksum. The `fix` option only applies to the PNG chunks, so it doesn't work for adler32 errors anyway.

**Comment by Tristan971** [comment]
Sure, we're not using (or interested in) `fix` anyway. Just pointed out that broken encoders do still exist in the wild 😅

**Comment by andrews05** [comment]
Yeah, for sure. I'd love to find out what they are and get them to fix it 😄

**Comment by Tristan971** [comment]
This is probably getting a bit off-topic but since you asked...

On one of the very few documented cases we have (user came to us for support, then insisted to take the time to reproduce the issue instead of just reexporting differently), it was Windows (no version information, but looks like Windows 10 from the window decorations) with GIMP 2.10.10, producing files failing with `CRC Mismatch in iCCP header` for the following settings: 

![](https://cdn.discordapp.com/attachments/404025002568974347/869270045279277116/unknown.png)

**Comment by andrews05** [comment]
Nice, thanks.
I researched this one and found it traced back to a bug in [exiv2](https://github.com/Exiv2/exiv2/issues/597) library. It's long since been fixed, but apparently existed for a while and resulted in the bug manifesting in programs using that library, including GIMP and digiKam, which in turn resulting in a lot of bad PNGs being created and escaping into the wild.

I haven't yet found anything related to bad Adler32 checksums, other than it's actually "normal" for PNG decoders to skip these anyway since it's redundant.

**Comment by Tristan971** [comment]
> I haven't yet found anything related to bad Adler32 checksums, other than it's actually "normal" for PNG decoders to skip these anyway since it's redundant. Perhaps we should make fix apply to this too (except I don't think libdeflate will allow it).

Personally I quite like overzealous checks for our use-case, as we've seen many wild edge-cases permitted by specs but breaking things badly, but we understand if it's a pain to maintain and is considered FP-like.

**Comment by andrews05** [comment]
Don’t worry, it’s not something we currently have control over since the deflate library we use doesn’t expose any options for it. And even so we would only want to skip it if `—fix` was set.

**Comment by andrews05** [comment]
@Tristan971 I just had a thought: Do you get people uploading APNGs at all? The current release of oxipng rejects these as unsupported but they *will* be supported in the next release. Would that be undesirable for your checks, or will it not matter?

**Comment by Tristan971** [comment]
@andrews05 Yes, but we are relying on imagemagick’s identify took to reject them so far, so that won’t be a problem 👍 (also glad to hear oxipng will support them; maybe we’ll revisit our own policy in that regard)

**Comment by andrews05** [comment]
Cool.
This may not be helpful but for reference, one option for dealing with APNGs is to use either `--keep` or `--strip` to remove all animation data, turning them into a standard single-frame png.

**Comment by Tristan971** [comment]
We’ll look at it when and if we decide to allow these. For GIFs we always pick the first frame for non-animated thumbnailing purpsoes, but I know some animated formats allow things like different canvas sizes per-frame and we always have to keep this kind of thing in mind (since we do enforce resolution limits). We’ll see, thanks for the mention anyway!

**Comment by andrews05** [comment]
This has been done in v9.

**Comment by abs-zer** [comment]
I **really like** the `--backup` option. Because after processing a file or a folder-full, I look in the folder to see whether all files got changed, or only some, and by how much. And then I manually delete the *.bak.png files. Without `--backup`, I would have to accept getting a "report" of what Oxipng did (which it grudgingly gives) and accept having **no way to roll back its actions**.

I **don't trust** a file compressor that casually overwrites the original files. I feel much safer when it renames the original file(s) and writes a new file(s). Most file editing programs do that, right? When I Save, the editor renames the old file and then writes a new file to the old filename. (Optionally, put the renamed file in the Recycle Bin? Just so long as it is not GONE.) That's why I use the --backup option.

I made these markups in my copy of CHANGELOG.md:
 `## Version 9.0.0`
 `- [Breaking] Remove `--backup` option. Use `--out` or `--dir` to preserve existing files.  ** ----- WHAT?? WHY?? ----- **`
 `...`
 `## Version 8.0.0    20221224    (POSSIBLY THE LAST USEFUL VERSION)    (used 20240507-`
 `...`

With version 8, I use a Windows .cmd file that does this for .png files (or wildcards):
`"%~dp0oxipng.exe" --zopfli --opt max --preserve --backup --verbose "%~1"`
and does this for a folder containing .png files:
`"%~dp0oxipng.exe" --zopfli --opt max --preserve --backup --verbose "%~1"\*.png`

Oxiping with ```--backup``` only backs up files that it changes. There is no easy substitute for having the compression program do this!

To get a somewhat similar result with Oxipng that now **lacks** `--backup`,

Possible method 1 (helpfully recommended): I would use a very different override of Oxipng's default behavior. I could make it write the output files (any that it actually writes) with different filenames (using `--out`) or into a different folder (using `--dir`). Making different filenames seems quite awkward if not impossible. I don't think Oxipng can generate the necessary modified filenames or filepaths to write to while it is processing an advanced wildcard filespec. I don't want a separate "tree" of compressed files. I would have to make the command processor generate the name-pairs, and run Oxipng once for each file. 

Possible method 2: I could rename *png to *.bak, run Oxipng on *.bak (if that is even possible), and then finally rename *.bak to *.png (all unmodified files would get back their original names; only the modified files would stay behind as *.bak when the 2nd renaming fails. But then every file got its Archive bit turned on in the process, very undesirable; maybe do another step to turn them off.

Possible method 3: I could (1) copy the files specified by the wildcard (or folder name), (3) run the compression, and then (#) delete the copies that are unchanged. (That would be pathetic.)

**Comment by andrews05** [comment]
Hi @abs-zer 
Sorry to hear this was important to you. If the alternatives are not acceptable to you, you can of course continue using version 8. I'm afraid we have no plans to reinstate the backup option at this time.

Here's a couple of other options you might consider:
- If you're concerned about the possibility of corrupting your images, you could build oxipng with the `sanity-checks` feature which validates that the output image still matches the original before overwriting any files.
- Use the `--dry-run` option to do an initial run and check that you're happy with the output report before committing to a real run.
